# Generated by Django 4.1 on 2022-11-02 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('jenis', models.CharField(max_length=15)),
                ('berat', models.IntegerField(null=True)),
                ('poin', models.FloatField(null=True)),
                ('bank_sampah', models.CharField(max_length=50)),
                ('donatur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donatur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
